package textilesJimenez;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

public class CuentaTotal extends javax.swing.JFrame {

    DefaultTableModel modelo;
    PreparedStatement us;
    
    public CuentaTotal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableSueteresNina = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableSueteresNino = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableChaleco = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGuardarChaleco = new javax.swing.JButton();
        btnGuardarNino = new javax.swing.JButton();
        btnGuardarNina = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuInicio = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuPedidos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuPagos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuPrestamos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuMateriaPrima = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Khmer MN", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cuenta Total");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 320, 60));

        tableSueteresNina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Modelo", "No. Orden", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane5.setViewportView(tableSueteresNina);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 400, 140));

        tableSueteresNino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Modelo", "No. Orden", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane3.setViewportView(tableSueteresNino);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 400, 140));

        tableChaleco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Modelo", "No. Orden", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane2.setViewportView(tableChaleco);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 400, 140));

        jLabel3.setFont(new java.awt.Font("Khmer MN", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Suéteres niña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 120, 30));

        jLabel5.setFont(new java.awt.Font("Khmer MN", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Chaleco");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Khmer MN", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Suéteres niño");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        btnGuardarChaleco.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardarChaleco.setFont(new java.awt.Font("Khmer MN", 1, 15)); // NOI18N
        btnGuardarChaleco.setText("Guardar");
        btnGuardarChaleco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarChalecoActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarChaleco, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 110, 50));

        btnGuardarNino.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardarNino.setFont(new java.awt.Font("Khmer MN", 1, 15)); // NOI18N
        btnGuardarNino.setText("Guardar");
        getContentPane().add(btnGuardarNino, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 110, 50));

        btnGuardarNina.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardarNina.setFont(new java.awt.Font("Khmer MN", 1, 15)); // NOI18N
        btnGuardarNina.setText("Guardar");
        getContentPane().add(btnGuardarNina, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 110, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/fondoMorado1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 510));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(370, 25));

        jMenu1.setText("Inicio");
        jMenu1.setFont(new java.awt.Font("Khmer MN", 1, 15)); // NOI18N

        menuInicio.setFont(new java.awt.Font("Khmer MN", 0, 14)); // NOI18N
        menuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/btnInicio.png"))); // NOI18N
        menuInicio.setText("Menú principal");
        menuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInicioActionPerformed(evt);
            }
        });
        jMenu1.add(menuInicio);

        menuSalir.setFont(new java.awt.Font("Khmer MN", 0, 14)); // NOI18N
        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/btnSalir.png"))); // NOI18N
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(menuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pedidos");
        jMenu2.setFont(new java.awt.Font("Khmer MN", 1, 15)); // NOI18N

        menuPedidos.setFont(new java.awt.Font("Khmer MN", 0, 14)); // NOI18N
        menuPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/btnModificar.png"))); // NOI18N
        menuPedidos.setText("Modificar");
        menuPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPedidosActionPerformed(evt);
            }
        });
        jMenu2.add(menuPedidos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Pagos");
        jMenu3.setFont(new java.awt.Font("Khmer MN", 1, 15)); // NOI18N

        menuPagos.setFont(new java.awt.Font("Khmer MN", 0, 14)); // NOI18N
        menuPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/btnModificar.png"))); // NOI18N
        menuPagos.setText("Modificar");
        menuPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPagosActionPerformed(evt);
            }
        });
        jMenu3.add(menuPagos);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Préstamos");
        jMenu4.setFont(new java.awt.Font("Khmer MN", 1, 15)); // NOI18N

        menuPrestamos.setFont(new java.awt.Font("Khmer MN", 0, 14)); // NOI18N
        menuPrestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/btnModificar.png"))); // NOI18N
        menuPrestamos.setText("Modificar");
        menuPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrestamosActionPerformed(evt);
            }
        });
        jMenu4.add(menuPrestamos);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Materia prima");
        jMenu5.setFont(new java.awt.Font("Khmer MN", 1, 15)); // NOI18N

        menuMateriaPrima.setFont(new java.awt.Font("Khmer MN", 0, 14)); // NOI18N
        menuMateriaPrima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/btnModificar.png"))); // NOI18N
        menuMateriaPrima.setText("Modificar");
        menuMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMateriaPrimaActionPerformed(evt);
            }
        });
        jMenu5.add(menuMateriaPrima);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInicioActionPerformed
        menuTextiles menu = new menuTextiles();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_menuInicioActionPerformed

    private void menuPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPedidosActionPerformed
        modificarPedidos pedidos = new modificarPedidos();
        this.setVisible(false);
        pedidos.setVisible(true);
    }//GEN-LAST:event_menuPedidosActionPerformed

    private void menuPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPagosActionPerformed
        pagoTrabajadores pago = new pagoTrabajadores();
        this.setVisible(false);
        pago.setVisible(true);
    }//GEN-LAST:event_menuPagosActionPerformed

    private void menuPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrestamosActionPerformed
        registroPrestamos prestamos = new registroPrestamos();
        this.setVisible(false);
        prestamos.setVisible(true);
    }//GEN-LAST:event_menuPrestamosActionPerformed

    private void menuMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMateriaPrimaActionPerformed
        MateriaPrima materia = new MateriaPrima();
        this.setVisible(false);
        materia.setVisible(true);
    }//GEN-LAST:event_menuMateriaPrimaActionPerformed

    private void btnGuardarChalecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarChalecoActionPerformed
        
    }//GEN-LAST:event_btnGuardarChalecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuentaTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuentaTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuentaTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuentaTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CuentaTotal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarChaleco;
    private javax.swing.JButton btnGuardarNina;
    private javax.swing.JButton btnGuardarNino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JMenuItem menuInicio;
    private javax.swing.JMenuItem menuMateriaPrima;
    private javax.swing.JMenuItem menuPagos;
    private javax.swing.JMenuItem menuPedidos;
    private javax.swing.JMenuItem menuPrestamos;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JTable tableChaleco;
    private javax.swing.JTable tableSueteresNina;
    private javax.swing.JTable tableSueteresNino;
    // End of variables declaration//GEN-END:variables

    conectar cc = new conectar();
    Connection cn = cc.conexion();
    
}
