package textilesJimenez;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MateriaPrima extends javax.swing.JFrame {

    DefaultTableModel modelo;
    PreparedStatement us;
    
    public MateriaPrima() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHilo = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuInicio = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuPedidos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuPagos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuPrestamos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuCuenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Khmer MN", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Materia prima");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 310, 70));

        tableHilo.setFont(new java.awt.Font("Khmer MN", 0, 14)); // NOI18N
        tableHilo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "No. Factura", "Kilos", "Total Neto"
            }
        ));
        jScrollPane1.setViewportView(tableHilo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 750, 250));

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Khmer MN", 1, 15)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 110, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/fondoMorado1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 510));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(327, 25));

        jMenu1.setText("Inicio");
        jMenu1.setFont(new java.awt.Font("Khmer MN", 1, 15)); // NOI18N

        menuInicio.setFont(new java.awt.Font("Khmer MN", 0, 14)); // NOI18N
        menuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/btnInicio.png"))); // NOI18N
        menuInicio.setText("Menú principal");
        menuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInicioActionPerformed(evt);
            }
        });
        jMenu1.add(menuInicio);

        menuSalir.setFont(new java.awt.Font("Khmer MN", 0, 14)); // NOI18N
        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/btnSalir.png"))); // NOI18N
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(menuSalir);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Pedidos");
        jMenu5.setFont(new java.awt.Font("Khmer MN", 1, 15)); // NOI18N

        menuPedidos.setFont(new java.awt.Font("Khmer MN", 0, 14)); // NOI18N
        menuPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/btnModificar.png"))); // NOI18N
        menuPedidos.setText("Modificar");
        menuPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPedidosActionPerformed(evt);
            }
        });
        jMenu5.add(menuPedidos);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Pagos");
        jMenu2.setFont(new java.awt.Font("Khmer MN", 1, 15)); // NOI18N

        menuPagos.setFont(new java.awt.Font("Khmer MN", 0, 14)); // NOI18N
        menuPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/btnModificar.png"))); // NOI18N
        menuPagos.setText("Modificar");
        menuPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPagosActionPerformed(evt);
            }
        });
        jMenu2.add(menuPagos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Préstamos");
        jMenu3.setFont(new java.awt.Font("Khmer MN", 1, 15)); // NOI18N

        menuPrestamos.setFont(new java.awt.Font("Khmer MN", 0, 14)); // NOI18N
        menuPrestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/btnModificar.png"))); // NOI18N
        menuPrestamos.setText("Modificar");
        menuPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrestamosActionPerformed(evt);
            }
        });
        jMenu3.add(menuPrestamos);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Cuenta");
        jMenu4.setFont(new java.awt.Font("Khmer MN", 1, 15)); // NOI18N

        menuCuenta.setFont(new java.awt.Font("Khmer MN", 0, 14)); // NOI18N
        menuCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/btnModificar.png"))); // NOI18N
        menuCuenta.setText("Modificar");
        menuCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCuentaActionPerformed(evt);
            }
        });
        jMenu4.add(menuCuenta);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInicioActionPerformed
        menuTextiles menu = new menuTextiles();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_menuInicioActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPedidosActionPerformed
        modificarPedidos pedidos = new modificarPedidos();
        this.setVisible(false);
        pedidos.setVisible(true);
    }//GEN-LAST:event_menuPedidosActionPerformed

    private void menuPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPagosActionPerformed
        pagoTrabajadores pago = new pagoTrabajadores();
        this.setVisible(false);
        pago.setVisible(true);
    }//GEN-LAST:event_menuPagosActionPerformed

    private void menuPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrestamosActionPerformed
        registroPrestamos prestamos = new registroPrestamos();
        this.setVisible(false);
        prestamos.setVisible(true);
    }//GEN-LAST:event_menuPrestamosActionPerformed

    private void menuCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCuentaActionPerformed
        CuentaTotal cuenta = new CuentaTotal();
        this.setVisible(false);
        cuenta.setVisible(true);
    }//GEN-LAST:event_menuCuentaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            for (int i=0; i<tableHilo.getRowCount(); i++) {
                us = cn.prepareStatement("INSERT INTO materiaPrima (fecha, noFactura, kilos, totalNeto) VALUES (?,?,?,?)");
                us.setString(1, tableHilo.getValueAt(i, 0).toString());
                us.setString(2, tableHilo.getValueAt(i, 1).toString());
                us.setString(3, tableHilo.getValueAt(i, 2).toString());
                us.setString(4, tableHilo.getValueAt(i, 3).toString());
                if (JOptionPane.showConfirmDialog(null, "¿Agregar información factura?", "Confirmación", JOptionPane.YES_NO_OPTION)
                        == JOptionPane.YES_OPTION) {
                        us.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Datos actualizados");
                }
            }   
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MateriaPrima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuCuenta;
    private javax.swing.JMenuItem menuInicio;
    private javax.swing.JMenuItem menuPagos;
    private javax.swing.JMenuItem menuPedidos;
    private javax.swing.JMenuItem menuPrestamos;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JTable tableHilo;
    // End of variables declaration//GEN-END:variables

    conectar cc = new conectar();
    Connection cn = cc.conexion();
}
