package textilesJimenez;

public class menuTextiles extends javax.swing.JFrame {

    public menuTextiles() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        pedidos = new javax.swing.JButton();
        bordado = new javax.swing.JButton();
        factHilo = new javax.swing.JButton();
        pagosT = new javax.swing.JButton();
        cuenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Oriya MN", 1, 50)); // NOI18N
        jLabel2.setText("Textiles Jimenez");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        pedidos.setBackground(new java.awt.Color(0, 0, 0));
        pedidos.setFont(new java.awt.Font("Oriya MN", 0, 16)); // NOI18N
        pedidos.setForeground(new java.awt.Color(255, 255, 255));
        pedidos.setText("Pedidos");
        pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidosActionPerformed(evt);
            }
        });
        getContentPane().add(pedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 160, 60));

        bordado.setBackground(new java.awt.Color(0, 0, 0));
        bordado.setFont(new java.awt.Font("Oriya MN", 0, 16)); // NOI18N
        bordado.setForeground(new java.awt.Color(255, 255, 255));
        bordado.setText("Bordado");
        bordado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bordadoActionPerformed(evt);
            }
        });
        getContentPane().add(bordado, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 160, 60));

        factHilo.setBackground(new java.awt.Color(0, 0, 0));
        factHilo.setFont(new java.awt.Font("Oriya MN", 0, 16)); // NOI18N
        factHilo.setForeground(new java.awt.Color(255, 255, 255));
        factHilo.setText("Fact. Hilo");
        factHilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factHiloActionPerformed(evt);
            }
        });
        getContentPane().add(factHilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 160, 60));

        pagosT.setBackground(new java.awt.Color(0, 0, 0));
        pagosT.setFont(new java.awt.Font("Oriya MN", 0, 16)); // NOI18N
        pagosT.setForeground(new java.awt.Color(255, 255, 255));
        pagosT.setText("Pago trabajadores");
        pagosT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagosTActionPerformed(evt);
            }
        });
        getContentPane().add(pagosT, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 200, 60));

        cuenta.setBackground(new java.awt.Color(0, 0, 0));
        cuenta.setFont(new java.awt.Font("Oriya MN", 0, 16)); // NOI18N
        cuenta.setForeground(new java.awt.Color(255, 255, 255));
        cuenta.setText("Cuenta");
        cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaActionPerformed(evt);
            }
        });
        getContentPane().add(cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 160, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidosActionPerformed
        pedidos pedidos1 = new pedidos();
        pedidos1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pedidosActionPerformed

    private void bordadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bordadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bordadoActionPerformed

    private void factHiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factHiloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factHiloActionPerformed

    private void pagosTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagosTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagosTActionPerformed

    private void cuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuTextiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuTextiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuTextiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuTextiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuTextiles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bordado;
    private javax.swing.JButton cuenta;
    private javax.swing.JButton factHilo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton pagosT;
    private javax.swing.JButton pedidos;
    // End of variables declaration//GEN-END:variables
}
