package textilesJimenez;

public class menuTextiles extends javax.swing.JFrame {

    /**
     * Creates new form menuTextiles
     */
    public menuTextiles() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnModficarPedidos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnPagoTrabajadores = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnPrestamos = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnMateriaPrima = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnCuenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Khmer MN", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Textiles Jiménez");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, 60));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Khmer MN", 0, 16)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModficarPedidos.setBackground(new java.awt.Color(0, 0, 0));
        btnModficarPedidos.setFont(new java.awt.Font("Khmer MN", 1, 16)); // NOI18N
        btnModficarPedidos.setForeground(new java.awt.Color(255, 255, 255));
        btnModficarPedidos.setText("Modificar");
        btnModficarPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModficarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModficarPedidosActionPerformed(evt);
            }
        });
        jPanel1.add(btnModficarPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 110, 50));

        jTabbedPane1.addTab("Pedidos", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPagoTrabajadores.setBackground(new java.awt.Color(0, 0, 0));
        btnPagoTrabajadores.setFont(new java.awt.Font("Khmer MN", 1, 16)); // NOI18N
        btnPagoTrabajadores.setForeground(new java.awt.Color(255, 255, 255));
        btnPagoTrabajadores.setText("Pagos");
        btnPagoTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoTrabajadoresActionPerformed(evt);
            }
        });
        jPanel2.add(btnPagoTrabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 110, 50));

        jTabbedPane1.addTab("Pagos", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrestamos.setBackground(new java.awt.Color(0, 0, 0));
        btnPrestamos.setFont(new java.awt.Font("Khmer MN", 1, 16)); // NOI18N
        btnPrestamos.setForeground(new java.awt.Color(255, 255, 255));
        btnPrestamos.setText("Modificar");
        btnPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamosActionPerformed(evt);
            }
        });
        jPanel3.add(btnPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 110, 50));

        jTabbedPane1.addTab("Préstamos", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMateriaPrima.setBackground(new java.awt.Color(0, 0, 0));
        btnMateriaPrima.setFont(new java.awt.Font("Khmer MN", 1, 16)); // NOI18N
        btnMateriaPrima.setForeground(new java.awt.Color(255, 255, 255));
        btnMateriaPrima.setText("Modificar");
        btnMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriaPrimaActionPerformed(evt);
            }
        });
        jPanel4.add(btnMateriaPrima, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 110, 50));

        jTabbedPane1.addTab("Materia prima", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCuenta.setBackground(new java.awt.Color(0, 0, 0));
        btnCuenta.setFont(new java.awt.Font("Khmer MN", 1, 16)); // NOI18N
        btnCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnCuenta.setText("Modificar");
        btnCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentaActionPerformed(evt);
            }
        });
        jPanel5.add(btnCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 110, 50));

        jTabbedPane1.addTab("Cuenta", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 470, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/fondoMorado1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 450));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(50, 23));
        jMenuBar1.setSize(new java.awt.Dimension(86, 18));

        jMenu1.setText("Inicio");
        jMenu1.setFont(new java.awt.Font("Kannada Sangam MN", 0, 14)); // NOI18N

        menuSalir.setFont(new java.awt.Font("Kannada Sangam MN", 0, 14)); // NOI18N
        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/btnSalir.png"))); // NOI18N
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(menuSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void btnCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentaActionPerformed
        CuentaTotal cuenta = new CuentaTotal();
        this.setVisible(false);
        cuenta.setVisible(true);
    }//GEN-LAST:event_btnCuentaActionPerformed

    private void btnPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamosActionPerformed
        registroPrestamos prestamos = new registroPrestamos();
        this.setVisible(false);
        prestamos.setVisible(true);
    }//GEN-LAST:event_btnPrestamosActionPerformed

    private void btnPagoTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoTrabajadoresActionPerformed
        pagoTrabajadores pagoTra = new pagoTrabajadores();
        this.setVisible(false);
        pagoTra.setVisible(true);
    }//GEN-LAST:event_btnPagoTrabajadoresActionPerformed

    private void btnModficarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModficarPedidosActionPerformed
        modificarPedidos modPedidos = new modificarPedidos();
        this.setVisible(false);
        modPedidos.setVisible(true);
    }//GEN-LAST:event_btnModficarPedidosActionPerformed

    private void btnMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriaPrimaActionPerformed
        MateriaPrima materia = new MateriaPrima();
        this.setVisible(false);
        materia.setVisible(true);
    }//GEN-LAST:event_btnMateriaPrimaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuTextiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuTextiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuTextiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuTextiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuTextiles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCuenta;
    private javax.swing.JButton btnMateriaPrima;
    private javax.swing.JButton btnModficarPedidos;
    private javax.swing.JButton btnPagoTrabajadores;
    private javax.swing.JButton btnPrestamos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem menuSalir;
    // End of variables declaration//GEN-END:variables
}
