package textilesJimenez;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

public class pagoTrabajadores extends javax.swing.JFrame {

    DefaultTableModel modelo;
    PreparedStatement us;
    
    public pagoTrabajadores() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTrabajadores = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuPrincipal = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuPedidos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuPrestamos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuMateriaPrima = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuCuenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Khmer MN", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pago trabajadores");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, 50));

        tableTrabajadores.setFont(new java.awt.Font("Khmer MN", 0, 16)); // NOI18N
        tableTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Fecha", "Total pago"
            }
        ));
        jScrollPane1.setViewportView(tableTrabajadores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 760, 250));

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Khmer MN", 1, 15)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 110, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/fondoMorado1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 510));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(378, 25));

        jMenu1.setText("Menú");
        jMenu1.setFont(new java.awt.Font("Khmer MN", 1, 15)); // NOI18N

        menuPrincipal.setFont(new java.awt.Font("Khmer MN", 0, 14)); // NOI18N
        menuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/btnInicio.png"))); // NOI18N
        menuPrincipal.setText("Menú principal");
        menuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrincipalActionPerformed(evt);
            }
        });
        jMenu1.add(menuPrincipal);

        menuSalir.setFont(new java.awt.Font("Khmer MN", 0, 14)); // NOI18N
        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/btnSalir.png"))); // NOI18N
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(menuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pedidos");
        jMenu2.setFont(new java.awt.Font("Khmer MN", 1, 15)); // NOI18N

        menuPedidos.setFont(new java.awt.Font("Khmer MN", 0, 14)); // NOI18N
        menuPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/btnModificar.png"))); // NOI18N
        menuPedidos.setText("Modificar");
        menuPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPedidosActionPerformed(evt);
            }
        });
        jMenu2.add(menuPedidos);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Préstamos");
        jMenu5.setFont(new java.awt.Font("Khmer MN", 1, 15)); // NOI18N

        menuPrestamos.setFont(new java.awt.Font("Khmer MN", 0, 14)); // NOI18N
        menuPrestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/btnModificar.png"))); // NOI18N
        menuPrestamos.setText("Modificar");
        menuPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrestamosActionPerformed(evt);
            }
        });
        jMenu5.add(menuPrestamos);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("Materia prima");
        jMenu3.setFont(new java.awt.Font("Khmer MN", 1, 15)); // NOI18N

        menuMateriaPrima.setFont(new java.awt.Font("Khmer MN", 0, 14)); // NOI18N
        menuMateriaPrima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/btnModificar.png"))); // NOI18N
        menuMateriaPrima.setText("Modificar");
        menuMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMateriaPrimaActionPerformed(evt);
            }
        });
        jMenu3.add(menuMateriaPrima);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Cuenta");
        jMenu4.setFont(new java.awt.Font("Khmer MN", 1, 15)); // NOI18N

        menuCuenta.setFont(new java.awt.Font("Khmer MN", 0, 14)); // NOI18N
        menuCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/btnModificar.png"))); // NOI18N
        menuCuenta.setText("Modificar");
        menuCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCuentaActionPerformed(evt);
            }
        });
        jMenu4.add(menuCuenta);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrincipalActionPerformed
        menuTextiles menuPrincipal = new menuTextiles();
        this.setVisible(false);
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_menuPrincipalActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMateriaPrimaActionPerformed
        MateriaPrima materia = new MateriaPrima();
        this.setVisible(false);
        materia.setVisible(true);
    }//GEN-LAST:event_menuMateriaPrimaActionPerformed

    private void menuPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPedidosActionPerformed
        modificarPedidos pedidos = new modificarPedidos();
        this.setVisible(false);
        pedidos.setVisible(true);
    }//GEN-LAST:event_menuPedidosActionPerformed

    private void menuPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrestamosActionPerformed
        registroPrestamos prestamos = new registroPrestamos();
        this.setVisible(false);
        prestamos.setVisible(true);
    }//GEN-LAST:event_menuPrestamosActionPerformed

    private void menuCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCuentaActionPerformed
        CuentaTotal cuenta = new CuentaTotal();
        this.setVisible(false);
        cuenta.setVisible(true);
    }//GEN-LAST:event_menuCuentaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            for(int i = 0; i < tableTrabajadores.getRowCount(); i++) {
                us = cn.prepareStatement("INSERT INTO pagoTrabajadores (nombre, fecha, total) VALUES (?,?,?)");
                us.setString(1, tableTrabajadores.getValueAt(i, 0).toString());
                us.setString(2, tableTrabajadores.getValueAt(i, 1).toString());
                us.setString(3, tableTrabajadores.getValueAt(i, 2).toString());
                if (JOptionPane.showConfirmDialog(null, "¿Agregar pagos?", "Confirmación", JOptionPane.YES_NO_OPTION)
                        == JOptionPane.YES_OPTION) {
                        us.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Datos actualizados");
                }
            }
        } catch(Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pagoTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pagoTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pagoTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pagoTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pagoTrabajadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuCuenta;
    private javax.swing.JMenuItem menuMateriaPrima;
    private javax.swing.JMenuItem menuPedidos;
    private javax.swing.JMenuItem menuPrestamos;
    private javax.swing.JMenuItem menuPrincipal;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JTable tableTrabajadores;
    // End of variables declaration//GEN-END:variables

    conectar cc = new conectar();
    Connection cn = cc.conexion();
}
